# Generated by Django 6.0.5 on 2026-05-21 19:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
