# Generated by Django 6.0.5 on 2026-06-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_items', '0002_alter_portfolioitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='project_period',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='tagline',
            field=models.CharField(default='', max_length=255),
        ),
    ]
