# Generated by Django 6.0.5 on 2026-06-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_items', '0003_portfolioitem_project_period_portfolioitem_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='order',
            field=models.IntegerField(default=0, help_text='Custom sort order. Lower numbers appear first. 0 is default.'),
        ),
    ]
