# Generated by Django 6.0.5 on 2026-06-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resume_url',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
