# Generated by Django 6.0.5 on 2026-05-24 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_stack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techstack',
            name='proficiency',
            field=models.PositiveIntegerField(default=80, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
