# Generated by Django 6.0.5 on 2026-06-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_stack', '0002_alter_techstack_proficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='techstack',
            name='icon_name',
            field=models.CharField(blank=True, choices=[('aws', 'AWS'), ('bootstrap', 'Bootstrap'), ('c', 'C'), ('cpp', 'C++'), ('css', 'CSS'), ('django', 'Django'), ('docker', 'Docker'), ('express', 'Express'), ('figma', 'Figma'), ('firebase', 'Firebase'), ('flask', 'Flask'), ('git', 'Git'), ('github', 'GitHub'), ('gcp', 'Google Cloud Platform'), ('graphql', 'GraphQL'), ('html', 'HTML'), ('js', 'JavaScript'), ('kubernetes', 'Kubernetes'), ('mongodb', 'MongoDB'), ('mysql', 'MySQL'), ('nextjs', 'Next.js'), ('nodejs', 'Node.js'), ('postgres', 'PostgreSQL'), ('py', 'Python'), ('react', 'React'), ('redis', 'Redis'), ('redux', 'Redux'), ('sass', 'Sass'), ('sqlite', 'SQLite'), ('tailwind', 'Tailwind CSS'), ('threejs', 'Three.js'), ('ts', 'TypeScript'), ('vue', 'Vue.js')], help_text='Select a pre-defined SVG icon from skillicons.dev. If blank, falls back to uploaded icon.', max_length=50, null=True),
        ),
    ]
