# Generated by Django 6.0.5 on 2026-06-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_stack', '0003_techstack_icon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techstack',
            name='icon_name',
            field=models.CharField(blank=True, help_text="Enter any pre-defined SVG icon key from skillicons.dev (e.g. 'py', 'django', 'react', 'fastapi', 'supabase'). See all keys at https://github.com/tandpfun/skill-icons#readme", max_length=50, null=True),
        ),
    ]
