# Generated by Django 6.0.5 on 2026-06-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_stack', '0005_alter_techstack_icon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techstack',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('tools', 'Tools'), ('cloud', 'Cloud'), ('devops', 'DevOps')], max_length=50),
        ),
    ]
