# Generated by Django 6.0.5 on 2026-06-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_stack', '0006_alter_techstack_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techstack',
            options={'ordering': ['category', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='techstack',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which this skill appears (lower numbers appear first)'),
        ),
    ]
