# Generated by Django 6.0.5 on 2026-06-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_stack', '0007_alter_techstack_options_techstack_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techstack',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('methodologies', 'Methodologies'), ('tools', 'Tools'), ('cloud', 'Cloud'), ('devops', 'DevOps')], max_length=50),
        ),
    ]
